version: "3.7"

services:

  db:
    image: postgres:12
    restart: always
    ports:
      - "25432:5432"
    volumes:
      - "${PWD}/.pgdata:/var/lib/postgresql/data:Z"
    environment:
      POSTGRES_DB: "${PGDATABASE}"
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"

  worker:
    build:
      dockerfile: "${PWD}/worker/Dockerfile"
      context: "${PWD}/worker"
    restart: always
    volumes:
      - "${PWD}/worker:/app"
      - "${PWD}/tmp:/app/tmp:z"
    environment:
      PGHOST: "db"
      PGPORT: "5432"
      PGDATABASE: "${PGDATABASE}"
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
      URL: "${URL}"
      PROXY: "${PROXY}"
    links:
      - db:db
    depends_on:
      - db

  api:
    build:
      dockerfile: "${PWD}/api/Dockerfile"
      context: "${PWD}/api"
    restart: always
    volumes:
      - "${PWD}/api:/app"
    environment:
      PGHOST: "db"
      PGPORT: "5432"
      PGDATABASE: "${PGDATABASE}"
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
    links:
      - db:db
    depends_on:
      - db

  nginx: 
    image: nginx:latest
    restart: always
    volumes:
      - ./web/nginx:/etc/nginx
      - ./web:/var/www/html
    links:
      - api:api
    ports:
      - 4580:80